package com.bean;

public enum Command {
	LOGIN,

	GET_USER_TABLE, GET_PRODUCT_TABLE, GET_CARGO_TABLE, GET_PRODUCTCARGO_TABLE, GET_POST_TABLE,

	DELETE_USER, DELETE_PRODUCT, DELETE_CARGO, DELETE_PRODUCTCARGO, DELETE_POST,

	ADD_USER, ADD_PRODUCT, ADD_CARGO, ADD_PRODUCTCARGO, ADD_POST,

	UPDATE_USER, UPDATE_PRODUCT, UPDATE_CARGO, UPDATE_PRODUCTCARGO, UPDATE_POST;
}
